baseURL = "https://mansoorbarri.com"
languageCode = 'en-us'
title = "Mansoor Barri"

paginate = 5
[menu]
  [[menu.main]]
    name = "blogs"
    url = "/blogs"
    weight = 1

  [[menu.main]]
    name = "tags"
    url = "/tags"
    weight = 2

[params]
  description = "known for a few things. creator of Sehat Saathi, Hugo theme Validator, and a few other things."
  wiki = "likh."
  hero = "just a **techie**."
  search = true
  mainSections = ["blogs"]
  projects = [    
      {name = "pdfthing", url = "https://pdfthing.mansoorbarri.com", description = "a PDF utility done right."},       
      {name = "coming Soon", url = "https://github.com/mansoorbarri/coming-soon/", description = "A hugo theme for your website pre-public look."},       
      {name = "hugo validator", url = "https://github.com/mansoorbarri/hugo-validator", description = "A theme submission validation script for Hugo."},       
  ]
  socials = [        
  {name = "github", url = "https://github.com/mansoorbarri"},
  {name = "linkedin", url = "https://www.linkedin.com/in/mansoorbarri/"},
  {name = "x", url = "https://x.com/mansoorbarri"},
  ]

[outputs]
  home = ["HTML", "CSS", "JS"]
