name = "website"
compatibility_date = "2025-06-12"

[assets]
directory = "./public"

routes = [
  { pattern = "mansoorbarri.com", custom_domain = true }
  { pattern = "www.mansoorbarri.com", custom_domain = true }
]
